# ScrapeConfig is how Services of type external name can be scraped
# https://github.com/prometheus-operator/prometheus-operator/issues/218
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  labels:
    metricssource: cert-manager
    cluster: workloads
    prometheus: k8s
  name: cert-manager-workloads
  namespace: monitoring
spec:
  staticConfigs:
  - targets:
    - cert-manager-metrics-egress.monitoring.svc:9402
